### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ortuagustin** [elganzua124/practicaoo2#2]
Hola, estuve mirando un poco rapido el TP. Algunas cosas para corregir

Esto lo vi en el modelo y tests, asi que aplica a ambos casos.

Al redefinir un método, en muchos casos es necesario recordar invocar al metodo de la superclase. Es muy comun que hayan errores por olvidar este detalle, mas que nada en metodos como `#initialize` y `#setUp`. Incluso el propio Pharo tira un warning recomendando esto. Hace poco un alumno en el foro tenia un problema que era justamente por eso, por olvidar un `super initialize` en una subclase, entonces, la inicializacion que hacia el ancestro, se perdia en la clase de mas abajo de la jerarquia.

# Tests: 

1. `#testGestQuestionsFromTopic` podria chequear algun caso mas interesante. Ahora mismo esta validando que si un topico no tiene preguntas, devuelve colección vacía. Debería haber tests para los casos donde los topicos tienen preguntas.. casos donde una pregunta esté en más de un topico, etc

> Los tests que agregan/eliminan objetos a una coleccion, si bien es correcto mirar la cantidad de elementos de la coleccion, no es suficiente (por ej. si agrego un numero cualquiera, el test pasa porque pase de tener 0 elementos a 1). Lo ideal es verificar que el elemento que quise agregar, realmente esté en la colecccion (o no esté, en caso de eliminar)

2. Una sugerencia para `#testGetScoreFromUser`. No está mal como está ahora, pero lo que yo haria para quedarme tranquilo, es testear un escenario en donde:

    1. Parto de un score X
    2. Agrego un like y verifico el score
    3. Elimino 1 o 2 likes y verifico el score
    4. Borro la pregunta y verifico el score

   Es decir, "jugar" un poco con las clases, haciendolas interactuar para ir viendo que cada interacción es consistente.. Simplemente para asegurarme que esté todo bien

3. **AnswerTest** no tiene tests
4. **UserTest**: no deberian hacer uso de CuOOra soleInstance en los tests. Las variables globales complican todo en los tests porque no se reinician entre cada test; entonces, de esta manera, los tests no son independientes entre si. Lo que haga un test con esa variable global, puede repercutir en otro test

 # No hacer tests de UI!!.

**Comment by ortuagustin** [comment]
# Modelo:
1. Yo agregaria un metodo `#questions` en CuOOra que me devuelva todas las preguntas. La implementación podria ser la que esta en `#getRelevantQuestionsForUser` (el flatCollect). De esa manera, eliminan la variable temporal y se puede reutilizar la funcionalidad de obtener todas las preguntas del sistema

2. En `#getScoreFromUser`, hay envidia de atributos. Mover el metodo a la clase Usuario y eliminar de CuOOra; de esa forma, ademas, se ahorran el problema de verificar si el usuario existe o no.

3. Un detalle super menor es que la convencion de los `accessors` es `#topics` (para el caso del "getter" y no `getTopics`), y `#topics: aCollection` (para el caso del "setter")

4. No estoy 100% seguro ya que nunca la usé, pero la clase **IdentitySet**, por el nombre, parece indicar que compara los objetos por identidad (en otras palabras, el mismo puntero). Creo que para el caso sería mejor usar **Set** y luego implementar dos metodos. [Acá está explicado](https://ci.inria.fr/pharo-contribution/job/UpdatedPharoByExample/lastSuccessfulBuild/artifact/book-result/Collections/Collections.html). Busquen en esa pagina (ctrl + F) la seccion **92.5**

**Comment by elganzua124** [comment]
Joya, gracias Agustín! Vamos a corregir los puntos que bien marcaste.

**Comment by elganzua124** [comment]
Bueno, lo cierro. Ya subí a la plataforma el TP. Si es necesario realizar modificaciones, se puede abrir o crear otro issue.
